Repository founders-programme-2/commons, pull requests merged in 2019-04, with the labels that each got.

#12 Setup/basic project setup
  .travis.yml
  client/.eslintrc.js
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/serviceWorker.js
  package.json
Labels: awaiting-review

#13 travis-badge-in-README
  README.md
Labels: approved

#23 Setup/basic server deployment
  client/package.json
  package-lock.json
  package.json
  server/app.js
Labels: approved

#35 Setup/setup component folder
  client/package-lock.json
  client/package.json
  client/src/component/common/footer/footer.js
  client/src/component/common/header/Header.js
Labels: awaiting-review

#34 Setup/setup basic styling
  client/package-lock.json
  client/package.json
  client/src/assets/challenge.svg
  client/src/assets/conversation.svg
  client/src/assets/file.svg
  client/src/assets/instruction.svg
  client/src/assets/lightbulb.svg
  client/src/assets/logo.svg
  client/src/assets/network.svg
  client/src/assets/numbered.svg
  client/src/assets/star.svg
  client/src/assets/tools.svg
  client/src/index.css
  package-lock.json
Labels: awaiting-review

#39 link-codecov-to-travis
  .travis.yml
  README.md
Labels: awaiting-review

#42 Feature/header component
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Component/Common/Header/index.js
  client/src/Component/Common/Header/index.style.js
  client/src/Component/Common/Menu/Menu.js
  client/src/Component/Common/Menu/index.js
  client/src/Component/Common/Menu/index.style.js
  client/src/Component/views/About.js
  client/src/Component/views/Home.js
  client/src/Component/views/HowTo.js
  client/src/Component/views/KeyTerms.js
  client/src/Component/views/Methods.js
  client/src/Component/views/Play.js
  client/src/Component/views/Theory.js
  client/src/Component/views/Workshop.js
  client/src/component/common/footer/footer.js
  client/src/component/common/header/Header.js
  client/src/component/views/Home.js
  client/src/index.css
  client/src/index.js
  package-lock.json
Labels: approved

#41 Feature/Footer component
  client/package-lock.json
  client/src/App.js
  client/src/Component/Common/Footer/Footer.style.js
  client/src/Component/Common/Footer/index.js
  client/src/Component/Common/Header/Header.style.js
  client/src/Component/views/About.js
  client/src/Component/views/About/index.js
  client/src/Component/views/About/index.style.js
  package-lock.json
Labels: awaiting-review, component

#44 Feature/create banner component
  client/src/App.js
  client/src/Component/Common/Banner/index.js
  client/src/Component/Common/Banner/index.style.js
  client/src/Component/views/Home.js
  client/src/Component/views/Landing.js
  client/src/component/common/banner/index.js
  client/src/index.css
Labels: approved

#46 Feature/banner pages
  client/src/App.js
  client/src/Component/Common/Banner/index.js
  client/src/Component/Common/Banner/index.style.js
  client/src/Component/views/Error404.js
  client/src/Component/views/ErrorResources.js
  client/src/component/common/banner/index.js
  client/src/index.css
Labels: awaiting-review

#47 Menu functionality
  client/src/App.js
  client/src/Component/Common/Header/Header.style.js
  client/src/Component/Common/Header/index.js
  client/src/Component/Common/Menu/Menu.js
  client/src/Component/Common/Menu/index.js
  client/src/Component/Common/Menu/index.style.js
  client/src/Component/views/About/index.js
  client/src/Component/views/Landing.js
  client/src/index.js
Labels: awaiting-review

#45 View header and footer in all layouts
  client/src/App.js
  client/src/Component/views/HowTo.js
  client/src/Component/views/HowTo/index.js
  client/src/Component/views/HowTo/inedx.style.js
  client/src/Component/views/KeyTerms.js
  client/src/Component/views/KeyTerms/index.js
  client/src/Component/views/KeyTerms/index.style.js
  client/src/Component/views/Methods.js
  client/src/Component/views/Methods/index.js
  client/src/Component/views/Methods/index.style.js
  client/src/Component/views/Play.js
  client/src/Component/views/Play/index.js
  client/src/Component/views/Play/index.style.js
  client/src/Component/views/Theory.js
  client/src/Component/views/Theory/index.js
  client/src/Component/views/Theory/index.style.js
  client/src/Component/views/Workshop/index.js
  client/src/Component/views/Workshop/index.style.js
  client/src/assets/key.svg
  client/src/assets/scroll.svg
Labels: awaiting-review

#51 intial menu styling - background and child elements
  client/package-lock.json
  client/src/Component/Common/Header/index.style.js
  client/src/Component/Common/Menu/index.js
  client/src/Component/Common/Menu/index.style.js
  client/src/index.css
  package-lock.json
Labels: approved

#53 apply-error-404-page
  client/src/App.js
  client/src/index.js
Labels: approved

#58 Banner Component Footer
  client/package-lock.json
  client/package.json
  client/src/Component/Common/Banner/index.js
  client/src/Component/Common/Banner/index.style.js
  client/src/Component/Common/BannerFooter/index.js
  client/src/Component/Common/BannerFooter/index.style.js
  client/src/Component/Common/Button/index.js
  client/src/Component/Common/Button/index.style.js
  client/src/Component/Common/Menu/index.style.js
  client/src/Component/views/Error404.js
  client/src/Component/views/ErrorResources.js
  client/src/Component/views/Landing.js
  client/src/index.css
  client/src/index.js
Labels: approved

#54 Feature/game play
  client/package-lock.json
  client/src/Component/views/Play/index.js
  client/src/Component/views/Play/index.style.js
Labels: request change

#55 Fix/refactor footer button
  client/src/Component/Common/Footer/Footer.style.js
  client/src/Component/Common/Footer/index.js
  client/src/Component/views/About/index.js
  client/src/Component/views/HowTo/index.js
  client/src/Component/views/Methods/index.js
  client/src/Component/views/Play/index.js
Labels: approved

#60 Feature/game play
  client/src/Component/Common/Button/index.js
  client/src/Component/Common/Button/index.style.js
  client/src/Component/views/Play/index.js
Labels: approved

#59 Feature/method selection
  client/src/Component/views/MethodCard/index.js
  client/src/Component/views/MethodCard/index.style.js
  client/src/Component/views/Methods/index.js
  client/src/Component/views/Methods/index.style.js
  client/src/index.css
Labels: awaiting-review

#61 Feature/instructions page
  client/src/Component/views/HowTo/index.js
  client/src/Component/views/HowTo/index.style.js
  client/src/Component/views/HowTo/inedx.style.js
  client/src/Component/views/Play/index.js
  client/src/fakeData/instruction.js
  client/src/index.js
Labels: approved

#65 Feature/priorities page
  client/src/App.js
  client/src/Component/views/MethodCard/index.js
  client/src/Component/views/Methods/index.js
  client/src/Component/views/Priorities/index.js
  client/src/Component/views/Priorities/index.style.js
Labels: approved

#66 Fix/update resource from card
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Component/Common/Footer/index.js
  client/src/Component/views/ErrorNoMoreResources.js
  client/src/Component/views/MethodCard/index.js
  client/src/Component/views/Methods/index.js
  client/src/Component/views/Methods/index.style.js
  client/src/index.css
Labels: awaiting-review

#73 Feature/priorities tools
  client/package-lock.json
  client/src/App.js
  client/src/Component/views/MethodCard/index.js
  client/src/Component/views/MethodCard/index.style.js
  client/src/Component/views/Methods/index.js
  client/src/Component/views/Priorities/index.js
  client/src/Component/views/PrioritiesTools/index.js
  client/src/Component/views/PrioritiesTools/index.style.js
Labels: approved

#74 Create method card data and dynamically apply to method page
  client/src/Component/views/MethodCard/index.js
  client/src/Component/views/MethodCard/index.style.js
  client/src/Component/views/Methods/index.js
  client/src/fakeData/methodCardData.js
Labels: approved

#78 update font on menu
  client/src/Component/Common/Menu/index.style.js
Labels: approved

#90 Feature/add context
  client/src/App.js
  client/src/Component/views/MethodCard/index.js
  client/src/Component/views/Methods/index.js
  client/src/Context/ContextComponent.js
  client/src/fakeData/methodCardData.js
Labels: awaiting-review

#88 Feature/priorities func
  client/src/Component/views/MethodCard/index.js
  client/src/Component/views/PrioritiesTools/index.js
  client/src/Context/ContextComponent.js
Labels: approved

#77 Feature/theory
  client/src/Component/views/About/index.js
  client/src/Component/views/About/index.style.js
  client/src/Component/views/Persona/index.js
  client/src/Component/views/Persona/index.style.js
  client/src/Component/views/Theory/index.js
  client/src/Component/views/YourScenario/index.js
  client/src/Component/views/YourScenario/index.style.js
  client/src/assets/houses.svg
Labels: approved, merge-conflicts

#99 link logo to homepage
  client/src/Component/Common/Header/index.js
Labels: approved

#100 add shadow to prev & next button / update font styling on scenario btn
  client/src/Component/Common/Footer/Footer.style.js
  client/src/Component/Common/Footer/index.js
  client/src/Component/views/Methods/index.js
  client/src/Component/views/Methods/index.style.js
Labels: approved

#102 Feature/priority popup
  client/package-lock.json
  client/package.json
  client/src/Component/views/PrioritiesTools/index.js
Labels: approved

#103 Feature/favicon
  client/public/favicon.ico
  client/public/index.html
Labels: approved

#107 Fix/summary priorities integration
  client/src/App.js
  client/src/Component/Timeline/TimelineCards/index.js
  client/src/Component/Timeline/TimelineCards/index.style.js
  client/src/Component/Timeline/index.js
  client/src/Component/Timeline/index.style.js
  client/src/Component/views/PrioritiesTools/index.js
  client/src/Component/views/Summary/index.js
  client/src/Component/views/Summary/index.style.js
  client/src/assets/arrow.svg
Labels: approved

#112 Fix/simple responsive tweaks
  client/src/Component/Common/Banner/index.style.js
  client/src/Component/Common/BannerFooter/index.style.js
  client/src/index.css
Labels: approved

#111 fix selection highlight on menu x
  client/src/Component/Common/Menu/index.style.js
Labels: approved

#110 Feature/methods alerts
  client/src/App.js
  client/src/Component/Timeline/index.js
  client/src/Component/views/ErrorNoMoreResources.js
  client/src/Component/views/ErrorResources.js
  client/src/Component/views/HowTo/index.js
  client/src/Component/views/KeyTerms/index.js
  client/src/Component/views/MethodCard/index.js
  client/src/Component/views/Methods/index.js
  client/src/Component/views/PrioritiesTools/index.js
  client/src/data/instruction.js
  client/src/data/keyTerms.js
  client/src/data/methodCardData.js
Labels: approved

#62 create your scenario page and person
  client/package-lock.json
  client/src/App.js
  client/src/Component/views/Challenges/index.js
  client/src/Component/views/Challenges/index.style.js
  client/src/Component/views/HowTo/index.style.js
  client/src/Component/views/MethodCard/index.style.js
  client/src/Component/views/Persona/index.js
  client/src/Component/views/Play/index.js
  client/src/Component/views/YourScenario/index.js
  client/src/Component/views/YourScenario/index.style.js
  client/src/data/challenges.js
  client/src/data/persona.js
  package-lock.json
Labels: approved, merge-conflicts
